[tools]
bun = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
uv = "latest"
yarn = "latest"
deno = "latest"
terraform = "latest"
kubectl = "latest"
awscli = { version = "latest", symlink_bins = "true" }
gcloud = "latest"

[settings.ruby]
compile = false

