[tools]
awscli = "latest"
bun = "latest"
deno = "latest"
gcloud = "latest"
go = "latest"
herdr = "latest"
kubectl = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
uv = "latest"
wrangler = "latest"
yarn = "latest"

[settings.ruby]
compile = false
